In [57]:
import wx
import dicom
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [58]:
def get_paths(wildcard):
    app = wx.App(None)
    style = wx.FD_OPEN | wx.FD_FILE_MUST_EXIST | wx.MULTIPLE
    dialog = wx.FileDialog(None, 'Open', wildcard=wildcard, style=style)
    if dialog.ShowModal() == wx.ID_OK:
        paths = dialog.GetPaths()
    else:
        paths = None
    dialog.Destroy()
    return paths

In [68]:
# Load dicom 2D distribution (reference image)
plan = dicom.read_file('C:\Users\Roy\Desktop\Exp4\Datos\Tailandia\Siriraj\planed distribution\CIRS Phantom IMRT .dcm')
planed_array = plan.pixel_array*plan.DoseGridScaling*100.0
planed_array = planed_array.astype(np.float32)

planed_size = planed_array.shape
print planed_size

(256L, 256L)


In [71]:
# Load dosimetry image

filepaths = get_paths('*.tif')
#filename_film = filename_film.encode('utf-8')
dosis_image_color = cv2.imread(filepaths[0],-1)
dosis_array = dosis_image_color[:,:,2].astype(np.float32) 

#film_array = 2.0*film_array/film_array.max() # esto es un escaleo arbitrario, debe ser remplazado por la calibracion

#film_size = film_image_color.shape
#print film_size

print dosis_image_color


[[[  0   0   0]
  [  0   0 332]
  [  0   0 332]
  ..., 
  [  0   0  81]
  [  0   0  73]
  [  0   0  73]]

 [[  0   0 338]
  [  0   0 332]
  [  0   0 318]
  ..., 
  [  0   0  68]
  [  0   0  61]
  [  0   0  69]]

 [[  0   0 321]
  [  0   0 332]
  [  0   0 316]
  ..., 
  [  0   0  63]
  [  0   0  61]
  [  0   0  66]]

 ..., 
 [[  0 324 484]
  [  0 325 495]
  [  0 326 485]
  ..., 
  [  0 252 238]
  [  0 251 238]
  [  0 250 243]]

 [[  0 325 483]
  [  0 326 493]
  [  0 327 483]
  ..., 
  [  0 251 240]
  [  0 250 238]
  [  0 249 239]]

 [[  0 325 255]
  [  0 326 495]
  [  0 327 495]
  ..., 
  [  0 250 249]
  [  0 249 245]
  [  0 249 245]]]


In [73]:
color_limits = [planed_array.min(),planed_array.max(),dosis_array.min(),dosis_array.max()]

plt.figure()#figsize = (20,20)

plt.subplot(121)
plt.imshow(planed_array , cmap = 'gray')
#plt.axis('off') # to hide tick values on X and Y axis
plt.clim(color_limits[0],color_limits[1])

plt.subplot(122)
plt.imshow(dosis_array , cmap = 'gray', interpolation = 'nearest')
#plt.axis('off')
plt.clim(color_limits[2],color_limits[3])

plt.show()